ovn_cluster/count-containers: remove whitespace from container name
ovn-org/ovn-fake-multinode pull request #50
Opened 2021-08-16 12:08 UTC by mohammadheib

when validating the container status on function count-containers
if the name of the container contains any whitespace the container will not be found
by count-containers, and that causes the functions that use count-containers
to run forever and waiting for the desired container to become up.

so we must remove the extra whitespace from the container name if exist.

Signed-off-by: Mohammad Heib <mheib@redhat.com>
Signed-off-by: Mohammad Heib <goody698@gmail.com>

2021-08-16 13:21 UTC, flavio-fernandes requested changes
One little nit. Otherwise, LGTM!

2021-08-16 13:21 UTC, flavio-fernandes commented on ovn_cluster.sh
> +  name=`echo $name | sed 's/ //g'`
Please replace back ticks with $():
```
name=$(echo $name | sed 's/ //g')
```

2021-08-16 15:13 UTC, mohammadheib commented
@flavio-fernandes Done!!,
Thanks:)

2021-08-17 03:20 UTC, flavio-fernandes approved these changes

2021-08-18 20:04 UTC, numansiddique approved these changes

2021-08-18 20:04 UTC, merged