Kepp sources around
ovn-org/ovn-fake-multinode pull request #60
Opened 2022-04-14 11:00 UTC by almusil

When the OVN and OvS is compiled from source
keep them around after the container is built.
It is very useful for debugging.

Signed-off-by: Ales Musil <amusil@redhat.com>

2022-04-14 11:01 UTC, almusil commented
@dceara @numansiddique Please take a look, I find it useful but you might have different opinion.

2022-04-14 11:31 UTC, dceara commented
@almusil I think it's fine.  It might increase the container image but it's up to the user then to make sure that the source directories that are used for building the image don't contain more than just the required sources (e.g., .git can be quite large if the source is a git repo).

2022-04-14 11:40 UTC, almusil commented
I have also added `make clean`, so the final image is larger, but the huge contribution is mostly the git objects.

2022-04-14 12:06 UTC, flavio-fernandes commented
> I have also added `make clean`, so the final image is larger, but the huge contribution is mostly the git objects.

One trick to help on that is to use a depth + shallow clone:

https://github.com/ovn-org/ovn-fake-multinode/blob/3af81872e7ff2a8966489d58fb48243f98093887/provisioning/grab_ovn_src.sh#L12

`--depth 1`

Not sure if that trick can be useful here.

2022-04-14 12:16 UTC, almusil commented
> > I have also added `make clean`, so the final image is larger, but the huge contribution is mostly the git objects.
> 
> One trick to help on that is to use a depth + shallow clone:
> 
> https://github.com/ovn-org/ovn-fake-multinode/blob/3af81872e7ff2a8966489d58fb48243f98093887/provisioning/grab_ovn_src.sh#L12
> 
> `--depth 1`
> 
> Not sure if that trick can be useful here.

That's great thing when you are getting like "fresh" clone, but for repo that you usually keep around for development it won't sadly help.

2022-04-14 14:01 UTC, numansiddique commented
@dceara will this affect the image sizeof the built container images  in the ovn-heater jobs ?

2022-04-14 15:25 UTC, dceara commented
> @dceara will this affect the image sizeof the built container images in the ovn-heater jobs ?

I just did a test and the ovn-heater generated image increased in size from 1.1GB to 1.43GB.

But then I moved to [shallow clones](https://github.com/dceara/ovn-heater/pull/101) in ovn-heater and the image size became 1.25GB.

If we also make sure the OVS submodule is [initialized in a shallow way](https://github.com/dceara/ovn-fake-multinode/commit/67536be3f7e9e711cdaf22ab79daf9f14df210da) and use `make distclean` instead of `make clean` then the image size becomes 1.22GB.

I think that's acceptable.

2022-04-14 17:22 UTC, flavio-fernandes commented
Ack. All in all....
/lgtm

2022-04-15 15:18 UTC, dceara requested changes
Let's also use a shallow clone for the OVS submodule, e.g.:
https://github.com/dceara/ovn-fake-multinode/commit/67536be3f7e9e711cdaf22ab79daf9f14df210da

2022-04-15 15:18 UTC, dceara commented on install_ovn.sh
> +make clean
Let's use `make distclean` instead.

2022-04-15 15:18 UTC, dceara commented on install_ovn.sh
> +make clean
Ditto.

2022-04-15 15:18 UTC, dceara commented on install_ovn.sh
> +make clean
Here too.

2022-04-19 05:40 UTC, almusil commented on install_ovn.sh
> +make clean
Done

2022-04-19 05:40 UTC, almusil commented on install_ovn.sh
> +make clean
Done

2022-04-19 05:40 UTC, almusil commented on install_ovn.sh
> +make clean
Done

2022-04-19 08:29 UTC, dceara approved these changes
LGTM, thanks!

2022-04-19 08:29 UTC, merged